### ISSUE TITLE
А COUNT может вернуть не число (если вы составили запрос правильно)?

### ISSUE THREAD

**Issue by coursar** [Desire456/spring-course-2#6]
https://github.com/Desire456/spring-course-2/blob/82bd34fdae417907fc16b02a51f8d3d6c169b36a/src/main/java/org/example/repository/UserRepositoryImpl.java#L29-L31

**Comment by Desire456** [comment]
По идее не может. Подскажите, пожалуйста, что я упускаю?

**Comment by coursar** [comment]
Если не может, то заключение в Optional с elseThrow не особо осмысленно. Вы возвращает всегда число, котрое либо 0, либо 1 (если username - unique и пароль верный).

**Comment by coursar** [comment]
В таких случаях, обычно (не с логинами/паролями, т.к. пароли сверять в сервисе), вообще обычно возвращают `COUNT(*) <> 0` в виде `boolean` и этого достаточно.
